version: "3"

services:
  v2ray:
    image: ghcr.io/getimages/v2ray:latest
    container_name: v2ray_bridge
    restart: always
    command: [ "v2ray", "-config=/etc/v2ray/config.json" ]
    ports:
      - ${SOCKS_PORT:-1010}:1010
      - ${SOCKS_PORT:-1010}:1010/udp
      - 127.0.0.1:${HTTP_PORT:-1110}:1110
      - ${SHADOWSOCKS_PORT:-1210}:1210
      - ${VMESS_PORT:-1310}:1310
    volumes:
      - ./config/:/etc/v2ray/
      - ./logs:/var/log/v2ray/
